### ISSUE TITLE
Logo Site GalsenDev

### ISSUE THREAD

**Issue by MedouneSGB** [Galsen-Dev-LAB/galsendev#12]
Hello je  pense qu'il serait plus joli et expressif de mettre un logo avec GalsenDev 
![image](https://user-images.githubusercontent.com/40875400/113424732-2a713c00-93c0-11eb-8b5f-40edd12954b6.png)

**Comment by NDOY3M4N** [comment]
Ce serait super. Je pense même qu'on peut prendre le logo du serveur Discord.

**Comment by MedouneSGB** [comment]
Oui je pense aussi !
Un logo plus grand ne serait pas mal

**Comment by NDOY3M4N** [comment]
Tu peux même essayer de faire un pull request.
