### ISSUE TITLE
Descendre un peu la barre header en scrolling mobile

### ISSUE THREAD

**Issue by MedouneSGB** [Galsen-Dev-LAB/galsendev#7]
Hello content de voir le site !
Descendre la barre d'un peu en scrolling mobile serait cool je pense
je trouve qu'il est un peu up.
![image](https://user-images.githubusercontent.com/40875400/103542713-40d92b80-4e95-11eb-83ce-ce4937f5c933.png)

**Comment by NDOY3M4N** [comment]
Hello @MedouneSGB, tu utilises quel navigateur pour l'affichage mobile? Firefox? Parce que même sur mon Firefox j'ai ce bug, par contre sur Chrome ou Brave je ne pas ce problème.

**Comment by NDOY3M4N** [comment]
C'est bon, c'est réglé! C'était un problème avec les **overflows**. Merci encore pour l'intervention

**Comment by MedouneSGB** [comment]
Cool c'est réglé..
![image](https://user-images.githubusercontent.com/40875400/103547411-47b76c80-4e9c-11eb-8384-a26029d567c4.png)

J'utilise Firefox pour le mobile (ctrl +maj+ m)
