### ISSUE TITLE
Some links are inacessible in the 'All Activities' page

### ISSUE THREAD

**Issue by NDOY3M4N** [Galsen-Dev-LAB/galsendev#9]
![issue_links](https://user-images.githubusercontent.com/46305144/103640726-73902c00-4f48-11eb-8726-b7271db66bef.png)

In this page, maybe we should hide these links since they only work when the user is in the homepage.

**Comment by daoodaba975** [comment]
Thank's @ NDOY3M4N I just noticed this error I will work on it later 👌🏽

**Comment by daoodaba975** [comment]
Hi @NDOY3M4N , the problem is solved now ✅
I just added the name of the anchor to the path so that it is accessible on all pages.

**Comment by NDOY3M4N** [comment]
Good job 🙏🏾.
